#!/usr/bin/env python3
import os, sys, subprocess, datetime, socket

def run(cmd):
    try:
        return subprocess.check_output(cmd, shell=True, text=True, stderr=subprocess.DEVNULL).strip()
    except Exception:
        return "N/A"

def check(title, passed, detail=""):
    status = "PASS" if passed else "FAIL"
    color = "#27ae60" if passed else "#e74c3c"
    return f'<tr><td>{title}</td><td style="color:{color};font-weight:bold">{status}</td><td>{detail}</td></tr>'

hostname = socket.gethostname()
today = datetime.date.today()

checks = []

# SSH checks
sshd = open("/etc/ssh/sshd_config").read() if os.path.exists("/etc/ssh/sshd_config") else ""
checks.append(check("PermitRootLogin no", "PermitRootLogin no" in sshd, "sshd_config"))
checks.append(check("MaxAuthTries <= 4", any(f"MaxAuthTries {i}" in sshd for i in range(1,5))))

# SELinux
se = run("getenforce")
checks.append(check("SELinux Enforcing", se == "Enforcing", se))

# Firewall
fw = run("systemctl is-active firewalld")
checks.append(check("firewalld active", fw == "active", fw))

# Password quality
pwq = run("grep minlen /etc/security/pwquality.conf")
checks.append(check("Password minlen >= 14", "minlen = 14" in pwq or "minlen=14" in pwq, pwq))

rows = "\n".join(checks)
css = (
    "body{font-family:Arial,sans-serif;margin:40px;background:#f5f5f5}"
    "h1{color:#2c3e50}"
    "table{width:100%;border-collapse:collapse;background:#fff}"
    "th{background:#2c3e50;color:#fff;padding:12px}"
    "td{padding:10px;border-bottom:1px solid #ddd}"
    "tr:hover{background:#f9f9f9}"
    ".meta{color:#7f8c8d;font-size:0.9em}"
)
html = (
    "<!DOCTYPE html><html><head><meta charset='utf-8'>"
    f"<title>Compliance Report - {hostname}</title>"
    f"<style>{css}</style></head><body>"
    "<h1>CIS Compliance Report</h1>"
    f"<p class='meta'>Host: {hostname} | Date: {today} | Generated by compliance-reporting</p>"
    "<table><tr><th>Check</th><th>Status</th><th>Detail</th></tr>"
    f"{rows}</table></body></html>"
)

out = f"/var/reports/compliance/report_{hostname}_{today}.html"
os.makedirs(os.path.dirname(out), exist_ok=True)
open(out, "w").write(html)
print(f"HTML report saved: {out}")
